FROM python:3

WORKDIR /usr/src/app/

COPY faceweb ./

RUN pip install --no-cache-dir -r requirements.txt
RUN python manage.py migrate

ENTRYPOINT  ["python", "manage.py", "runserver", "0.0.0.0:3000"]