# Generated by Django 3.0.4 on 2020-03-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primarykey', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='uploads/videos')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
