# Generated by Django 2.2.4 on 2020-05-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_auto_20200522_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclass',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, null=True)),
                ('ClassRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.StudentClass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.TeacherClass')),
            ],
        ),
    ]
