# Generated by Django 2.2.4 on 2020-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0007_auto_20200522_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
