# Generated by Django 2.2.4 on 2020-05-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0009_auto_20200523_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='ClassRoom',
            new_name='classRoom',
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('classRoom', 'day', 'hour')},
        ),
    ]
