# Generated by Django 2.2.4 on 2020-05-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0010_auto_20200523_0652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
