# Generated by Django 2.2.4 on 2020-05-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0011_delete_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceLogs',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
        migrations.DeleteModel(
            name='TeacherClass',
        ),
    ]
