# Generated by Django 2.2.4 on 2020-05-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0012_auto_20200523_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
