# Generated by Django 2.2.4 on 2020-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faceapp', '0013_auto_20200523_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('classRoom', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
