# Generated by Django 2.2.4 on 2020-05-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0017_studentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.StudentClass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.TeacherClass')),
            ],
        ),
    ]
