# Generated by Django 2.2.4 on 2020-05-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0018_attendancelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=50)),
                ('hour', models.IntegerField(default=0)),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.ClassRoom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.Subject')),
            ],
            options={
                'unique_together': {('classRoom', 'day', 'hour')},
            },
        ),
    ]
