# Generated by Django 2.2.4 on 2020-05-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0019_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='faceapp.Teacher'),
        ),
    ]
