# Generated by Django 2.2.4 on 2020-05-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0021_auto_20200525_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='faceapp.Subject'),
            preserve_default=False,
        ),
    ]
