# Generated by Django 2.2.4 on 2020-05-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0022_attendancelogs_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelogs',
            name='classRoom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='faceapp.ClassRoom'),
            preserve_default=False,
        ),
    ]
