# Generated by Django 2.2.4 on 2020-06-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0023_attendancelogs_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='last_class',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='no_of_classes',
            field=models.IntegerField(default=0),
        ),
    ]
