# Generated by Django 2.2.4 on 2020-06-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0024_auto_20200601_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclass',
            name='last_class',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
